import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "black-leather-boot",
    name: "بوت چرم مشکی",
    gender: "male",
    category: "بوت و نیم بوت",
    price: 2450000,
    beforePrice: 2150000,
    image: "/images/products/boot/1/1.webp",
    secondImage: "/images/products/boot/1/2.webp",
    images: [
      "/images/products/boot/1/1.webp",
      "/images/products/boot/1/2.webp",
      "/images/products/boot/1/3.webp",
    ],
    colors: ["#000000", "#6B4226"],
    sizes: ["40", "41", "42", "43"],
    stock: 12,
    description: "بوت چرمی مشکی با طراحی ساده و زیره ضدلغزش.",
  },
  {
    id: "2",
    slug: "brown-winter-boot",
    name: "نیم بوت زمستانی قهوه‌ای",
    gender: "male",
    category: "بوت و نیم بوت",
    price: 2890000,
    beforePrice: 2590000,
    image: "/images/products/boot/2/1.webp",
    secondImage: "/images/products/boot/2/2.webp",
    images: [
      "/images/products/boot/2/1.webp",
      "/images/products/boot/2/2.webp",
      "/images/products/boot/2/3.webp",
    ],
    colors: ["#6B4226"],
    sizes: ["41", "42", "43"],
    stock: 7,
    description: "نیم بوت گرم و مقاوم مناسب فصل سرد.",
  },
  {
    id: "3",
    slug: "classic-black-boot",
    name: "بوت کلاسیک مشکی",
    gender: "male",
    category: "بوت و نیم بوت",
    price: 3190000,
    beforePrice: 2790000,
    image: "/images/products/boot/3/1.webp",
    secondImage: "/images/products/boot/3/2.webp",
    images: [
      "/images/products/boot/3/1.webp",
      "/images/products/boot/3/2.webp",
      "/images/products/boot/3/3.webp",
    ],
    colors: ["#000000"],
    sizes: ["40", "41", "42"],
    stock: 0,
    description: "بوت کلاسیک با ظاهری رسمی و دوخت تمیز.",
  },
  {
    id: "4",
    slug: "casual-ankle-boot",
    name: "بوت نیم ساق راحتی",
    gender: "male",
    category: "بوت و نیم بوت",
    price: 1980000,
    beforePrice: 1750000,
    image: "/images/products/boot/4/1.webp",
    secondImage: "/images/products/boot/4/2.webp",
    images: [
      "/images/products/boot/4/1.webp",
      "/images/products/boot/4/2.webp",
      "/images/products/boot/4/3.webp",
    ],
    colors: ["#C3B091", "#808080"],
    sizes: ["40", "41", "42", "43"],
    stock: 5,
    description: "بوت سبک و راحت برای استفاده روزمره.",
  },
  {
    id: "5",
    slug: "suede-chelsea-boot",
    name: "بوت جیر چلسی",
    gender: "male",
    category: "بوت و نیم بوت",
    price: 2650000,
    beforePrice: 2350000,
    image: "/images/products/boot/5/1.webp",
    secondImage: "/images/products/boot/5/2.webp",
    images: [
      "/images/products/boot/5/1.webp",
      "/images/products/boot/5/2.webp",
      "/images/products/boot/5/3.webp",
    ],
    colors: ["#D4A017", "#6B4226"],
    sizes: ["41", "42", "43", "44"],
    stock: 18,
    description: "بوت چلسی جیر با کشسان کناری و فرم شیک.",
  },
  {
    id: "6",
    slug: "military-tactical-boot",
    name: "بوت تاکتیکی نظامی",
    gender: "male",
    category: "بوت و نیم بوت",
    price: 3350000,
    beforePrice: 2990000,
    image: "/images/products/boot/6/1.webp",
    secondImage: "/images/products/boot/6/2.webp",
    images: [
      "/images/products/boot/6/1.webp",
      "/images/products/boot/6/2.webp",
      "/images/products/boot/6/3.webp",
    ],
    colors: ["#000000", "#C3B091"],
    sizes: ["42", "43", "44"],
    stock: 3,
    description: "بوت مقاوم با کفی نرم و دوام بالا.",
  },
  {
    id: "7",
    slug: "black-formal-shoe",
    name: "کفش کلاسیک مشکی",
    gender: "male",
    category: "کلاسیک",
    price: 2250000,
    beforePrice: 1950000,
    image: "/images/products/classic/1/1.webp",
    secondImage: "/images/products/boot/1/2.webp",
    images: [
      "/images/products/boot/1/1.webp",
      "/images/products/boot/1/2.webp",
      "/images/products/boot/1/3.webp",
    ],
    colors: ["#000000"],
    sizes: ["40", "41", "42", "43"],
    stock: 9,
    description: "کفش کلاسیک مشکی مناسب مراسم و محیط کاری.",
  },
  {
    id: "8",
    slug: "brown-leather-shoe",
    name: "کفش چرم قهوه‌ای",
    gender: "male",
    category: "کلاسیک",
    price: 2390000,
    beforePrice: 2090000,
    image: "/images/products/classic/2/1.webp",
    secondImage: "/images/products/boot/2/2.webp",
    images: [
      "/images/products/boot/2/1.webp",
      "/images/products/boot/2/2.webp",
      "/images/products/boot/2/3.webp",
    ],
    colors: ["#6B4226"],
    sizes: ["41", "42", "43"],
    stock: 0,
    description: "کفش چرمی قهوه‌ای با ظاهری رسمی و شیک.",
  },
  {
    id: "9",
    slug: "oxford-classic-shoe",
    name: "کفش آکسفورد کلاسیک",
    gender: "male",
    category: "کلاسیک",
    price: 2790000,
    beforePrice: 2450000,
    image: "/images/products/classic/3/1.webp",
    secondImage: "/images/products/boot/3/2.webp",
    images: [
      "/images/products/boot/3/1.webp",
      "/images/products/boot/3/2.webp",
      "/images/products/boot/3/3.webp",
    ],
    colors: ["#000000", "#6B4226"],
    sizes: ["40", "41", "42"],
    stock: 14,
    description: "کفش آکسفورد با طراحی کلاسیک و دوخت مستحکم.",
  },
  {
    id: "10",
    slug: "derby-formal-shoe",
    name: "کفش دربی رسمی",
    gender: "male",
    category: "کلاسیک",
    price: 2590000,
    beforePrice: 2290000,
    image: "/images/products/classic/4/1.webp",
    secondImage: "/images/products/boot/4/2.webp",
    images: [
      "/images/products/boot/4/1.webp",
      "/images/products/boot/4/2.webp",
      "/images/products/boot/4/3.webp",
    ],
    colors: ["#000000"],
    sizes: ["41", "42", "43", "44"],
    stock: 6,
    description: "کفش دربی رسمی با کفی راحت و فرم استاندارد.",
  },
  {
    id: "11",
    slug: "soft-comfy-slipper",
    name: "کفش راحتی نرم",
    gender: "male",
    category: "راحتی",
    price: 980000,
    beforePrice: 850000,
    image: "/images/products/comfy/1/1.webp",
    secondImage: "/images/products/comfy/1/2.webp",
    images: [
      "/images/products/comfy/1/1.webp",
      "/images/products/comfy/1/2.webp",
      "/images/products/comfy/1/3.webp",
    ],
    colors: ["#808080", "#191970"],
    sizes: ["39", "40", "41", "42"],
    stock: 21,
    description: "کفش راحتی نرم مناسب استفاده روزمره.",
  },
  {
    id: "12",
    slug: "daily-casual-shoe",
    name: "کفش روزمره راحتی",
    gender: "male",
    category: "راحتی",
    price: 1150000,
    beforePrice: 990000,
    image: "/images/products/comfy/2/1.webp",
    secondImage: "/images/products/comfy/2/2.webp",
    images: [
      "/images/products/comfy/2/1.webp",
      "/images/products/comfy/2/2.webp",
      "/images/products/comfy/2/3.webp",
    ],
    colors: ["#000000", "#808080"],
    sizes: ["40", "41", "42", "43"],
    stock: 2,
    description: "کفش روزمره سبک با کفی نرم و انعطاف‌پذیر.",
  },
  {
    id: "13",
    slug: "lightweight-walking-shoe",
    name: "کفش پیاده‌روی سبک",
    gender: "male",
    category: "راحتی",
    price: 1290000,
    beforePrice: 1090000,
    image: "/images/products/comfy/3/1.webp",
    secondImage: "/images/products/comfy/3/2.webp",
    images: [
      "/images/products/comfy/3/1.webp",
      "/images/products/comfy/3/2.webp",
      "/images/products/comfy/3/3.webp",
    ],
    colors: ["#191970"],
    sizes: ["40", "41", "42"],
    stock: 11,
    description: "کفش پیاده‌روی سبک و مناسب استفاده طولانی.",
  },
  {
    id: "14",
    slug: "memory-foam-slipper",
    name: "کفش راحتی حافظه‌دار",
    gender: "male",
    category: "راحتی",
    price: 1350000,
    beforePrice: 1190000,
    image: "/images/products/comfy/4/1.webp",
    secondImage: "/images/products/comfy/4/2.webp",
    images: [
      "/images/products/comfy/4/1.webp",
      "/images/products/comfy/4/2.webp",
      "/images/products/comfy/4/3.webp",
    ],
    colors: ["#6B4226", "#C3B091"],
    sizes: ["41", "42", "43"],
    stock: 0,
    description: "کفش راحتی با کفی حافظه‌دار و حس نرمی.",
  },
  {
    id: "15",
    slug: "breathable-mesh-shoe",
    name: "کفش توری خنک",
    gender: "male",
    category: "راحتی",
    price: 890000,
    beforePrice: 760000,
    image: "/images/products/comfy/5/1.webp",
    secondImage: "/images/products/comfy/5/2.webp",
    images: [
      "/images/products/comfy/5/1.webp",
      "/images/products/comfy/5/2.webp",
      "/images/products/comfy/5/3.webp",
    ],
    colors: ["#000000", "#808080"],
    sizes: ["39", "40", "41", "42"],
    stock: 8,
    description: "کفش توری خنک با تهویه مناسب برای روزهای گرم.",
  },
  {
    id: "16",
    slug: "everyday-comfort-shoe",
    name: "کفش راحتی همه‌روزه",
    gender: "male",
    category: "راحتی",
    price: 1050000,
    beforePrice: 920000,
    image: "/images/products/comfy/6/1.webp",
    secondImage: "/images/products/comfy/6/2.webp",
    images: [
      "/images/products/comfy/6/1.webp",
      "/images/products/comfy/6/2.webp",
      "/images/products/comfy/6/3.webp",
    ],
    colors: ["#191970", "#808080"],
    sizes: ["40", "41", "42", "43"],
    stock: 4,
    description: "کفش راحتی همه‌روزه با طراحی ساده و مقاوم.",
  },
];